export const CATEGORIES = [
  'All',
  'Veg-Soup',
  'Chicken-Soup',
  'Salads',
  'Beverages',
  'Veg-Starters',
  'Tandoori-Starters',
  'Chicken-Starters',
  'Egg-Starters',
  'Sunday Special',
  'Andhra Special Non-Veg Starters',
  'Mutton-Starters', 
  'Seafood-Starters',
  'Combos',
  'Biriyanis',
  'Family pack Biriyanis',
  'Indian Breads',
  'Veg curries',
  'Chicken curries',
  'Sea food & Egg curries',
  'Mutton curries',
  'Rice items',
  'Noodles'
  
];

export const INITIAL_MENU = [
  {
    id: 1,
    name: 'Veg Lemon Coriander Soup',
    category: 'Veg-Soup',
    price: 99,
    type: 'Veg',
    description:
      'Fresh, light veg soup with zesty lemon and aromatic coriander—perfectly soothing and refreshing..',
      image:'/images/veg_lemon_coriander_soup.png',
     
  },
  {
    id: 2,
    name: 'Veg Manchow Soup',
    category: 'Veg-Soup',
    price: 99,
    type: 'Veg',
    description: 'Spicy Indo-Chinese veg soup loaded with veggies, garlic, and crispy noodle topping.',
    image:'/images/veg_manchow_soup.png',
    
  },
  {
    id: 3,
    name: 'Veg Hot & Sour Soup',
    category: 'Veg-Soup',
    price: 99,
    type: 'Veg',
    description:
      'Tangy and spicy veg soup with a perfect balance of sour flavors and crunchy vegetables.',
      image:'/images/veg_hot&sour_soup.png',
    
  },
  {
    id: 4,
    name: 'Mr Biriyani Special Soup',
    category: 'Veg-Soup',
    price: 109,
    type: 'Veg',
    description:
      'A unique blend of aromatic spices and fresh vegetables, creating a rich and flavorful soup that captures the essence of our signature biriyani in every spoonful.',
      image:'/images/mrbiriyani_special_ soup_veg.png',
    
  },
  {
    id: 5,
    name: 'Chicken Lemon Coriander Soup',
    category: 'Chicken-Soup',
    price: 109,
    type: 'Non-Veg',
    description:
      'Fresh, light chicken soup with zesty lemon and aromatic coriander—perfectly soothing and refreshing..',
      image:'/images/chicken_lemon_coriander_soup.png',
  },
  {
    id: 6,
    name: 'Chicken Manchow Soup',
    category: 'Chicken-Soup',
    price: 109,
    type: 'Non-Veg',
    description: 'Spicy Indo-Chinese chicken soup loaded with veggies, garlic, and crispy noodle topping.',
    image:'/images/chicken_manchow_soup.png',
  },
  {
    id: 7,
    name: 'Chicken Hot & Sour Soup',
    category: 'Chicken-Soup',
    price: 109,
    type: 'Non-Veg',
    description:
      'Tangy and spicy chicken soup with a perfect balance of sour flavors and crunchy vegetables.',
      image:'/images/chicken_hot&sour_soup.png',
  },
  {
    id: 8,
    name: 'Mr Biriyani Special Soup',
    category: 'Chicken-Soup',
    price: 119,
    type: 'Non-Veg',
    description:
      'A unique blend of aromatic spices and fresh chicken, creating a rich and flavorful soup that captures the essence of our signature biriyani in every spoonful.',
      image:'/images/mrbiriyani_special_soup_chicken.png',
  },
  {
    id: 9,
    name: 'Roasted papad',
    category: 'Salads',
    price: 19,
    type: 'Veg',
    description:'Crispy roasted papad—light, crunchy, and the perfect side to complement your meal.',
    image:'/images/roasted_papad.png',
  },
  {
    id: 10,
    name: 'Masala papad',
    category: 'Salads',
    price: 39,
    type: 'Veg',
    description:'Spicy masala papad—flavorful and aromatic, a perfect accompaniment to your main course.',
    image:'/images/masala_papad.png',
  },
  {
    id: 11,
    name: 'Cucumber salad',
    category: 'Salads',
    price: 49,
    type: 'Veg',
    description:'Crispy cucumber salad—refreshing and healthy, a perfect side to complement your meal.',
    image:'/images/cucumber_salad.png',
  },
  {
    id: 12,
    name: 'Green salad',
    category: 'Salads',
    price: 69,
    type: 'Veg',
    description:'Fresh green salad—crisp and nutritious, a perfect side to complement your meal.',
    image:'/images/green_salad.png',
  },
  {
     id: 13,
    name: 'Carrot salad',
    category: 'Salads',
    price: 59,
    type: 'Veg',
    description:'Crunchy carrot salad—fresh and nutritious, a perfect side to complement your meal.',
    image:'/images/carrot_salad.png',
  },
  {
    id: 14,
    name: 'Water Bottle(1 Ltr)',
    category: 'Beverages',
    price: 19,
    type: 'Veg',
    description:'Refresh yourself with our 1-liter water bottle—perfect for staying hydrated throughout the day.',
  },
  {
    id: 15,
    name: 'Cool Drinks(200 ml)',
    category: 'Beverages',
    price: 15,
    type: 'Veg',
    description:'Stay refreshed with our 200ml cool drink—perfect for quenching your thirst at any time.',
  },
  {
    id: 16,
    name: 'Cool Drinks(250 ml)',
    category: 'Beverages',
    price: 19,
    type: 'Veg',
    description:'Stay refreshed with our 250ml cool drink—perfect for quenching your thirst at any time.',
  },
  {
    id: 17,
    name: 'Cool Drinks(750 ml)',
    category: 'Beverages',
    price: 45,
    type: 'Veg',
    description:'Stay refreshed with our 750ml cool drink—perfect for quenching your thirst at any time.',
  },
  {
    id: 18,
    name: 'Butter Milk',
    category: 'Beverages',
    price: 25,
    type: 'Veg',
    description:'Cool, refreshing buttermilk spiced with salt and herbs—perfect for a light, soothing drink.',
  },
  {
    id: 19,
    name: 'Chilli Paneer',
    category: 'Veg-Starters',
    price: 169,
    type: 'Veg',
    description:'Spicy and flavorful paneer tossed with bell peppers, onions, and tangy chilli sauce.',
    image:'/images/chilli_paneer.png',
  },
  {
    id: 20,
    name: 'Paneer Pepper Dry',
    category: 'Veg-Starters',
    price: 169,
    type: 'Veg',
    description:'Flavorful paneer cooked in a spicy pepper dry masala—perfect for lovers of bold flavors.',
    image:'/images/paneer_pepper_dry.png',
  },
  {
    id: 21,
    name: 'Paneer 65',
    category: 'Veg-Starters',
    price: 169,
    type: 'Veg',
    description:'Crispy and flavorful paneer coated in a spicy 65 masala—perfect for those who love a bit of heat.',
    image:'/images/paneer_65.png',
  },
  {
    id: 22,
    name: 'Paneer Manchurian',
    category: 'Veg-Starters',
    price: 169,
    type: 'Veg',
    description:'Crispy and flavorful paneer in a tangy manchurian sauce—perfect for those who love a bit of spice.',
    image:'/images/paneer_manchurian.png',
  },
  {
    id: 23,
    name: 'Chilli Mushroom',
    category: 'Veg-Starters',
    price: 149,
    type: 'Veg',
    description:'Spicy and flavorful mushrooms tossed with bell peppers, onions, and tangy chilli sauce.',
    image:'/images/chilli_mushroom.png',
  },
  {
    id: 24,
    name: 'Mushroom Pepper Dry',
    category: 'Veg-Starters',
    price: 149,
    type: 'Veg',
    description:'Flavorful mushrooms cooked in a spicy pepper dry masala—perfect for lovers of bold flavors.',
    image:'/images/mushroom_pepper_dry.png',

  },
  {
    id: 25,
    name: 'Mushroom Manchurian',
    category: 'Veg-Starters',
    price: 149,
    type: 'Veg',
    description:'Crispy mushrooms tossed in a spicy, tangy Manchurian sauce with garlic and peppers.',
    image:'/images/mushroom_manchuria.png',
  },
  {
    id: 26,
    name: 'Mushroom 65',
    category: 'Veg-Starters',
    price: 149,
    type: 'Veg',
    description:'Crispy and flavorful mushrooms coated in a spicy 65 masala—perfect for those who love a bit of heat.',
    image:'/images/mushroom65.png',
  },
  {
    id: 27,
    name: 'Gobi Manchurian',
    category: 'Veg-Starters',
    price: 149,
    type: 'Veg',
    description:'Crispy cauliflower tossed in a spicy, tangy Manchurian sauce with garlic and peppers.',
    image:'/images/gobi_manchuria.png',
  },
  {
    id: 28,
    name: ' Gobi 65',
    category: 'Veg-Starters',
    price: 149,
    type: 'Veg',
    description:'Crispy and flavorful cauliflower coated in a spicy 65 masala—perfect for those who love a bit of heat.',
    image:'/images/gobi65.png',
  },
  {
    id: 29,
    name: 'chilli Gobi',
    category: 'Veg-Starters',
    price: 149,
    type: 'Veg',
    description:'Spicy and flavorful cauliflower tossed with bell peppers, onions, and tangy chilli sauce.',
    image:'/images/chilli_gobi.png',
  },
  {
    id: 30,
    name: 'Baby Corn Salt & Pepper',
    category: 'Veg-Starters',
    price: 129,
    type: 'Veg',
    description:'Crispy baby corn tossed in a savory salt and pepper sauce—perfect for a delightful snack.',
    image:'/images/babycorn_salt&pepper.png',
  },
  {
    id: 31,
    name: 'Chilli Baby Corn',
    category: 'Veg-Starters',
    price: 129,
    type: 'Veg',
    description:'Spicy and flavorful baby corn tossed with bell peppers, onions, and tangy chilli sauce.',
    image:'/images/chilli_babycorn.png',
  },
  {
    id: 32,
    name: 'Baby Corn 65',
    category: 'Veg-Starters',
    price: 129,
    type: 'Veg',
    description:'Crispy and flavorful baby corn coated in a spicy 65 masala—perfect for those who love a bit of heat.',
    image:'/images/babycorn65.png',
  },
  {
    id: 33,
    name: 'Baby Corn Manchurian',
    category: 'Veg-Starters',
    price: 129,
    type: 'Veg',
    description:'Crispy baby corn tossed in a spicy, tangy Manchurian sauce with garlic and peppers.',
    image:'/images/babycorn_manchuria.png',
  },
  {
    id: 34,
    name: 'Dragon Baby Corn',
    category: 'Veg-Starters',
    price: 139,
    type: 'Veg',
    description:'Crispy baby corn tossed in a fiery dragon sauce with garlic, ginger, and a hint of sweetness.',
    image:'/images/dragon_babycorn.png',
  },
  {
    id: 35,
    name: 'Dragon Paneer',
    category: 'Veg-Starters',
    price: 179,
    type: 'Veg',
    description:'Crispy paneer tossed in a fiery dragon sauce with garlic, ginger, and a hint of sweetness.',
    image:'/images/dragon_paneer.png',

  },
  {
    id: 36,
    name: 'Paneer Sholay Kabab',
    category: 'Veg-Starters',
    price: 169,
    type: 'Veg',
    description:'Crispy paneer cubes marinated in a blend of spices and herbs, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or snack.',
    image:'/images/paneer_sholay_kabab.png',
  },
  {
    id: 37,
    name: 'Chicken Tandoori(half)',
    category: 'Tandoori-Starters',
    price: 219,
    type: 'Non-Veg',
    description:'Juicy chicken pieces marinated in a blend of spices and yogurt, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/chicken_tandoori(half).png',
  },
  {
    id: 38,
    name: 'Chicken Tandoori(full)',
    category: 'Tandoori-Starters',
    price: 419,
    type: 'Non-Veg',
    description:'Juicy chicken pieces marinated in a blend of spices and yogurt, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/chicken_tandoori(full).png',
  },
  {
    id: 39,
    name: 'Kalmi Kabab(half)',
    category: 'Tandoori-Starters',
    price: 169,
    type: 'Non-Veg',
    description:'Juicy kalmi pieces marinated in a blend of spices and yogurt, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/kalmi_kabab(half).png',
  },
  {
    id: 40,
    name: 'Kalmi Kabab(full)',
    category: 'Tandoori-Starters',
    price: 299,
    type: 'Non-Veg',
    description:'Juicy kalmi pieces marinated in a blend of spices and yogurt, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/kalmi_kabab(full).png',
  },
  {
    id: 41,
    name: 'Tangadi Kabab',
    category: 'Tandoori-Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Juicy tangadi pieces marinated in a blend of spices and herbs, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/tangadi_kabab.png',
  },
  {
    id: 42,
    name: 'Hariyali Chicken Kabab',
    category: 'Tandoori-Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Juicy chicken pieces marinated in a blend of fresh herbs and spices, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/hariyali_chicken_kabab.png',
  },
  {
    id: 43,
    name: 'Banjara Chicken Kabab',
    category: 'Tandoori-Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Juicy chicken pieces marinated in a blend of spices and herbs, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/banjara_chicken_kabab.png',
  },
  {
    id: 44,
    name: 'Achari Chicken Tikka',
    category: 'Tandoori-Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Juicy chicken pieces marinated in a blend of pickling spices and herbs, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/achari_chicken_tikka.png',
  },
  {id: 45,
    name: 'Malai Chicken Tikka',
    category: 'Tandoori-Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Juicy chicken pieces marinated in a creamy blend of spices and herbs, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/malai_chicken_tikka.png',
  },
  {
    id: 46,
    name: 'Angara Chicken Tikka',
    category: 'Tandoori-Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Juicy chicken pieces marinated in a blend of spices and herbs, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/angara_chicken_kabab.png',
  },
  {
    id: 47,
    name: 'Chicken Seekh Kabab',
    category: 'Tandoori-Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Juicy minced chicken marinated in a blend of spices and herbs, then grilled to perfection on skewers—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/chicken_seekh_kabab.png',
  },
  {
    id: 48,
    name: 'Tandoori 65(half)',
    category: 'Tandoori-Starters',
    price: 219,
    type: 'Non-Veg',
    description:'Juicy chicken pieces coated in a spicy 65 masala, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/tandoori65_half.png',
  },
  {
    id: 49,
    name: 'Paneer Tikka',
    category: 'Tandoori-Starters',
    price: 199,
    type: 'Veg',
    description:'Juicy paneer cubes marinated in a blend of spices and yogurt, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or snack.',
    image:'/images/paneer_tikka.png',
  },
  {
    id: 50,
    name: 'Hot Garlick Wings(8 pcs)',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Juicy chicken wings tossed in a spicy garlic sauce—offering a flavorful and satisfying bite that’s perfect as a starter or snack.',
    image:'/images/hot_garlic_wings(8pcs).png',
  },
  {
    id: 51,
    name: 'Chilli Lollipop',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Crispy chicken lollipops coated in a spicy chili sauce—offering a flavorful and satisfying bite that’s perfect as a starter or snack.',
    image:'/images/chill_lollipop.png',
  },
  {
    id: 52,
    name: 'Dragon Chicken',
    category: 'Chicken-Starters',
    price: 189,
    type: 'Non-Veg',
    description:'Juicy chicken pieces marinated in a blend of spices and herbs, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/dragon_chicken.png',
  },
  {
    id: 53,
    name: 'Chicken Maharaja',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Juicy chicken pieces marinated in a blend of spices and herbs, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/chicken_maharaja.png',
  },
  {
    id: 54,
    name: 'Chicken 555',
    category: 'Chicken-Starters',
    price: 189,
    type: 'Non-Veg',
    description:'Crispy, spicy fried chicken tossed with garlic, curry leaves, and bold South Indian flavors.',
    image:'/images/chicken_555.png',
  },
  {
    id: 55,
    name: 'Wings Of Heaven',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Crispy chicken wings tossed in a spicy sauce—offering a flavorful and satisfying bite that’s perfect as a starter or snack.',
    image:'/images/wings_of_heaven.png',
  },
  {
    id: 56,
    name: 'Chicken Ghee Roast',
    category: 'Chicken-Starters',
    price: 189,
    type: 'Non-Veg',
    description:'Juicy chicken pieces cooked in a rich ghee-based sauce—offering a delicious and aromatic bite that’s perfect as a starter or main course.',
    image:'/images/chicken_ghee_roast.png',
  },
  {
    id: 57,
    name: 'Chicken Majestic',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Juicy chicken pieces marinated in a blend of spices and herbs, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
    image:'/images/chicken_majestic.png',
  },
  {
    id: 58,
    name: 'Lemon Chicken Dry',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Juicy chicken pieces cooked in a lemon-based sauce—offering a refreshing and flavorful bite that’s perfect as a starter or main course.',
    image:'/images/lemon_chicken_dry.png',
  },
  {
    id: 59,
    name: 'Pepper Chicken',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Juicy chicken pieces cooked in a spicy pepper-based sauce—offering a fiery and flavorful bite that’s perfect as a starter or main course.',
    image:'/images/pepper_chicken.png',
  },
  {
    id: 60,
    name: 'Chilli Chicken',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Juicy chicken pieces cooked in a spicy chili-based sauce—offering a fiery and flavorful bite that’s perfect as a starter or main course.',
    image:'/images/chilli_chicken.png',
  },
  {
    id: 61,
    name: 'Garlic Chicken Dry',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Juicy chicken pieces cooked in a garlic-based sauce—offering a rich and aromatic bite that’s perfect as a starter or main course.',
    image:'/images/garlic_chicken_dry.png',
  },
  {
    id: 62,
    name: 'Wings Pepper Dry',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Crispy chicken wings tossed in a spicy pepper sauce—offering a fiery and flavorful bite that’s perfect as a starter or snack.',
    image:'/images/wings_pepper_dry.png',
  },
  {
    id: 63,
    name: 'Sholay Chicken Kabab',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Juicy chicken kababs marinated in a blend of spices and herbs, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
  },
  {
    id: 64,
    name: 'Schezwan Chicken Dry',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Juicy chicken pieces cooked in a flavorful Schezwan-style sauce—offering a spicy and aromatic bite that’s perfect as a starter or main course.',
  },
  {
    id: 65,
    name: 'Chicken 65',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Spicy and flavorful chicken pieces cooked in a tangy sauce—offering a fiery and aromatic bite that’s perfect as a starter or main course.',
  },
  {
    id: 66,
    name: 'Kasturi Wings Dry',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Crispy chicken wings tossed in a rich, aromatic sauce—offering a flavorful bite that’s perfect as a starter or snack.',
  },
  {
    id: 67,
    name: 'Chicken kabab half',
    category: 'Chicken-Starters',
    price: 109,
    type: 'Non-Veg',
    description:'Juicy chicken kababs marinated in a blend of spices and herbs, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
  },
  {
    id: 68,
    name: 'Chicken kabab full',
    category: 'Chicken-Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Juicy chicken kababs marinated in a blend of spices and herbs, then grilled to perfection—offering a smoky, flavorful bite that’s perfect as a starter or main course.',
  },
  {
    id: 69,
    name: 'Chicken Lollipop Dry',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Crispy chicken lollipops tossed in a flavorful sauce—offering a delicious bite that’s perfect as a starter or snack',
  },
  {
    id: 70,
    name: 'Chicken Manchurian',
    category: 'Chicken-Starters',
    price: 179,
    type: 'Non-Veg',
    description:'Juicy chicken pieces cooked in a flavorful Manchurian-style sauce—offering a spicy and aromatic bite that’s perfect as a starter or main course.',
  },
  {
    id:71 ,
    name: 'Mr Biriyani Special Chicken',
    category: 'Chicken-Starters',
    price: 209,
    type: 'Non-Veg',
    description:'A special blend of aromatic spices and herbs, slow-cooked to perfection—offering a rich and flavorful bite that’s perfect as a starter or main course.',
  },
  {
    id:72 ,
    name: 'Boiled Egg',
    category: 'Egg-Starters',
    price: 29,
    type: 'Non-Veg',
    description:'Hard-boiled eggs served with a side of your choice—offering a simple and satisfying bite that’s perfect as a starter or snack.',
  },
  {
    id: 73,
    name: 'Egg Chilli',
    category: 'Egg-Starters',
    price: 119,
    type: 'Non-Veg',
    description:'Spicy and flavorful eggs cooked in a tangy sauce—offering a fiery and aromatic bite that’s perfect as a starter or main course.',
  },
  {
    id:74 ,
    name: 'Egg Burjji',
    category: 'Egg-Starters',
    price: 79,
    type: 'Non-Veg',
    description:'Flavorful eggs cooked in a rich, aromatic sauce—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id:75,
    name: 'Egg Pepper Dry',
    category: 'Egg-Starters',
    price: 119,
    type: 'Non-Veg',
    description:'Spicy and flavorful eggs cooked in a tangy sauce—offering a fiery and aromatic bite that’s perfect as a starter or main course.',
  },
  {
    id: 76,
    name: 'Egg Manchurian',
    category: 'Egg-Starters',
    price:129 ,
    type: 'Non-Veg',
    description:'Spicy and flavorful eggs cooked in a tangy sauce—offering a fiery and aromatic bite that’s perfect as a starter or main course.',
  },
  {
    id:77 ,
    name: 'Mutton Dum Biryani',
    category: 'Sunday Special',
    price:269 ,
    type: 'Non-Veg',
    description:'A rich and aromatic biryani made with tender mutton pieces—offering a hearty and flavorful bite that’s perfect as a main course.',
  },
  {
    id:78 ,
    name: 'Natu Kodi Biryani',
    category: 'Sunday Special',
    price:269 ,
    type: 'Non-Veg',
    description:'A rich and aromatic biryani made with tender Natu Kodi pieces—offering a hearty and flavorful bite that’s perfect as a main course.',
  },
  {
    id:79,
    name: 'Joint Biryani',
    category: 'Sunday Special',
    price:269 ,
    type: 'Non-Veg',
    description:'A rich and aromatic biryani made with tender joint pieces—offering a hearty and flavorful bite that’s perfect as a main course.',
  },
  {
    id:80 ,
    name: 'Gongura Chicken Biryani',
    category: 'Sunday Special',
    price:269 ,
    type: 'Non-Veg',
    description:'A rich and aromatic biryani made with tender chicken pieces—offering a hearty and flavorful bite that’s perfect as a main course.',
  },
  {
    id:81 ,
    name: 'Rainbow Biriyani',
    category: 'Sunday Special',
    price:209 ,
    type: 'Non-Veg',
    description:'A rich and aromatic biryani made with tender joint pieces—offering a hearty and flavorful bite that’s perfect as a main course.',
  },
  {
    id:82 ,
    name: 'Natu Kodi Fry',
    category: 'Sunday Special',
    price:220 ,
    type: 'Non-Veg',
    description:'Crispy fried Natu Kodi pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id:83 ,
    name: 'Andhra Chicken Fry',
    category: 'Andhra Special Non-Veg Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Crispy fried chicken pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id:84 ,
    name: 'Andhra Chilli Chicken',
    category: 'Andhra Special Non-Veg Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Spicy and flavorful chicken pieces cooked in a tangy sauce—offering a fiery and aromatic bite that’s perfect as a starter or main course.',  
  },
  {
    id: 85,
    name: 'Guntur Chicken Fry',
    category: 'Andhra Special Non-Veg Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Crispy fried chicken pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 86,
    name: 'Chicken Leg Roast',
    category: 'Andhra Special Non-Veg Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Tender chicken leg pieces roasted to perfection—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 87,
    name: 'Nellore Chicken Fry',
    category: 'Andhra Special Non-Veg Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Crispy fried chicken pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 88,
    name: 'Gongura Chicken Fry',
    category: 'Andhra Special Non-Veg Starters',
    price: 199,
    type: 'Non-Veg',
    description:'Crispy fried chicken pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 89,
    name: 'Mutton Kaju Fry',
    category: 'Andhra Special Non-Veg Starters',
    price: 249,
    type: 'Non-Veg',
    description:'Crispy fried mutton pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 90,
    name: 'Andhra Prawns Fry',
    category: 'Andhra Special Non-Veg Starters',
    price: 249,
    type: 'Non-Veg',
    description:'Crispy fried prawns pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 91,
    name: 'Anjal Fish Fry',
    category: 'Andhra Special Non-Veg Starters',
    price: 249,
    type: 'Non-Veg',
    description:'Crispy fried fish pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 92,
    name: 'Mutton Fry',
    category: 'Mutton-Starters',
    price: 249,
    type: 'Non-Veg',
    description:'Crispy fried mutton pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 93,
    name: 'Mutton Pepper Fry',
    category: 'Mutton-Starters',
    price: 249,
    type: 'Non-Veg',
    description:'Crispy fried mutton pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 94,
    name: 'Mutton Ghee Roast',
    category: 'Mutton-Starters',
    price: 249,
    type: 'Non-Veg',
    description:'Tender mutton pieces roasted in ghee—offering a rich and aromatic bite that’s perfect as a starter or main course.',
  },
  {
    id: 95,
    name: 'Mutton Kasturi Fry',
    category: 'Mutton-Starters',
    price: 249,
    type: 'Non-Veg',
    description:'Crispy fried mutton pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 96,
    name: 'Apollo Fish',
    category: 'Seafood-Starters',
    price: 239,
    type: 'Non-Veg',
    description:'Crispy fried fish pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 97,
    name: 'Fish Pepper Fry',
    category: 'Seafood-Starters',
    price: 239,
    type: 'Non-Veg',
    description:'Crispy fried fish pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 98,
    name: 'Chilli Fish',
    category: 'Seafood-Starters',
    price: 239,
    type: 'Non-Veg',
    description:'Crispy fried fish pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 99,
    name: 'Fish Manchurian',
    category: 'Seafood-Starters',
    price: 239,
    type: 'Non-Veg',
    description:'Crispy fried fish pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id:100 ,
    name: 'Chilli Prawns',
    category: 'Seafood-Starters',
    price: 249,
    type: 'Non-Veg',
    description:'Crispy fried prawns pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 101,
    name: 'Pepper Prawns',
    category: 'Seafood-Starters',
    price: 249,
    type: 'Non-Veg',
    description:'Crispy fried prawns pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id: 102,
    name: 'Prawns Manchurian',
    category: 'Seafood-Starters',
    price: 249,
    type: 'Non-Veg',
    description:'Crispy fried prawns pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id:103 ,
    name: 'Mr Biriyani Special Prawns',
    category: 'Seafood-Starters',
    price: 259,
    type: 'Non-Veg',
    description:'A special blend of prawns cooked in a flavorful sauce, served with steamed biriyani—offering a rich and satisfying meal.',
  },
  {
    id: 104,
    name: 'Kabab Combo',
    category: 'Combos',
    price: 199,
    type: 'Non-Veg',
    description:'A delicious assortment of juicy, smoky kebabs—perfectly grilled and full of rich flavors.',
  },
  {
    id: 105,
    name: 'Lollipo Combo',
    category: 'Combos',
    price: 219,
    type: 'Non-Veg',
    description:'A delightful selection of crispy, flavorful lollipos—perfect for a satisfying meal.',
  },
  {
    id:106 ,
    name: 'Chicken Tikka Combo',
    category: 'Combos',
    price: 239,
    type: 'Non-Veg',
    description:'A delicious assortment of juicy, smoky chicken tikka—perfectly grilled and full of rich flavors.',
  },
  {
    id:107,
    name: 'Kalmi Combo',
    category: 'Combos',
    price: 229,
    type: 'Non-Veg',
    description:'A delicious assortment of juicy, smoky kalmi—perfectly grilled and full of rich flavors.',
  },
  {
    id:108 ,
    name: 'Tandoori Combo',
    category: 'Combos',
    price: 259,
    type: 'Non-Veg',
    description:'A delicious assortment of juicy, smoky tandoori items—perfectly grilled and full of rich flavors.',
  },
  {
    id: 109,
    name: 'Tandoori 65 Combo',
    category: 'Combos',
    price: 269,
    type: 'Non-Veg',
    description:'A delicious assortment of juicy, smoky tandoori 65—perfectly grilled and full of rich flavors.',
  },
  {
    id: 110,
    name: 'Hyderabadi Ckn Dum Biryani',
    category: 'Biriyanis',
    price: 189,
    type: 'Non-Veg',
    description:'A flavorful blend of aromatic basmati rice and tender chicken, cooked to perfection in a rich, spiced sauce.',
  },
  {
    id: 111,
    name: 'Andhra Style Biryani',
    category: 'Biriyanis',
    price: 199,
    type: 'Non-Veg',
    description:'A spicy and flavorful biryani with a distinct Andhra twist, made with aromatic rice and tender meat.',
  },
  {
    id:112 ,
    name: 'Fry-Piece Chicken Biryani',
    category: 'Biriyanis',
    price: 199,
    type: 'Non-Veg',
    description:'A delicious blend of crispy chicken pieces and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:113 ,
    name: 'Guntur Chicken Biriyani',
    category: 'Biriyanis',
    price: 199,
    type: 'Non-Veg',
    description:'A fiery and flavorful biryani from Guntur, made with aromatic rice and tender chicken.',
  },
  {
    id:114 ,
    name: 'Rainbow Chicken Biriyani',
    category: 'Biriyanis',
    price: 209,
    type: 'Non-Veg',
    description:'A vibrant and flavorful biryani with a colorful array of ingredients, made with aromatic rice and tender chicken.',
  },
  {
    id:115,
    name: 'Kalmi Biryani',
    category: 'Biriyanis',
    price: 199,
    type: 'Non-Veg',
    description:'A delicious blend of tender kalmi and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:116,
    name: 'Tandoori 65 Biryani',
    category: 'Biriyanis',
    price: 229,
    type: 'Non-Veg',
    description:'A delicious blend of tandoori 65 and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:117 ,
    name: 'Chicken Tikka Biryani',
    category: 'Biriyanis',
    price: 199,
    type: 'Non-Veg',
    description:'A delicious blend of tender chicken tikka and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:118 ,
    name: 'Lollipop Juicy Biryani',
    category: 'Biriyanis',
    price: 199,
    type: 'Non-Veg',
    description:'A delicious blend of crispy lollipops and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:119,
    name: 'Kabab Biryani',
    category: 'Biriyanis',
    price: 189,
    type: 'Non-Veg',
    description:'A delicious blend of tender kababs and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id: 120,
    name: 'Chicken Wings Biryani',
    category: 'Biriyanis',
    price: 189,
    type: 'Non-Veg',
    description:'A delicious blend of tender chicken wings and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:121,
    name: 'Mr. Biriyani Special ',
    category: 'Biriyanis',
    price: 229,
    type: 'Non-Veg',
    description:'A special blend of aromatic basmati rice and tender meat, cooked to perfection in a rich, spiced sauce.',
  },
  {
    id: 122,
    name: 'Mutton Fry-Piece Biryani',
    category: 'Biriyanis',
    price: 249,
    type: 'Non-Veg',
    description:'A delicious blend of tender mutton pieces and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:123 ,
    name: 'Fish Biryani',
    category: 'Biriyanis',
    price: 239,
    type: 'Non-Veg',
    description:'A delicious blend of fresh fish and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:124 ,
    name: 'Prawns Biryani',
    category: 'Biriyanis',
    price: 249,
    type: 'Non-Veg',
    description:'A delicious blend of fresh prawns and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:125 ,
    name: 'Egg Biryani',
    category: 'Biriyanis',
    price: 129,
    type: 'Non-Veg',
    description:'A delicious blend of tender eggs and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:126 ,
    name: 'Paneer Biryani',
    category: 'Biriyanis',
    price: 179,
    type: 'Veg',
    description:'A delicious blend of tender paneer and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:127 ,
    name: 'Mushroom Biryani',
    category: 'Biriyanis',
    price: 169,
    type: 'Veg',
    description:'A delicious blend of tender mushrooms and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:128,
    name: 'Biriyani Rice',
    category: 'Biriyanis',
    price: 120,
    type: 'Veg',
    description:'A simple and delicious blend of aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:129 ,
    name: 'Hyderabadi Ckn Dum Biryani',
    category: 'Family pack Biriyanis',
    price: 549,
    type: 'Non-Veg',
    description:'A rich and flavorful biryani with a perfect blend of aromatic spices and tender chicken.',
  },
  {
    id: 130,
    name: 'Andhra Style Biryani',
    category: 'Family pack Biriyanis',
    price: 599,
    type: 'Non-Veg',
    description:'A spicy and flavorful biryani with a distinct Andhra twist, made with aromatic rice and tender meat.',
  },
  {
    id:131 ,
    name: 'Fry-Piece Chicken Biryani',
    category: 'Family pack Biriyanis',
    price: 599,
    type: 'Non-Veg',
    description:'A delicious blend of crispy chicken pieces and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:132 ,
    name: 'Guntur Chicken Biriyani',
    category: 'Family pack Biriyanis',
    price: 599,
    type: 'Non-Veg',
    description:'A fiery and flavorful biryani from Guntur, made with aromatic rice and tender chicken.',
  },
  {
    id:133 ,
    name: 'Rainbow Chicken Biriyani',
    category: 'Family pack Biriyanis',
    price: 629,
    type: 'Non-Veg',
    description:'A vibrant and flavorful biryani with a colorful array of ingredients, made with aromatic rice and tender chicken.',
  },
  {
    id:134,
    name: 'Kalmi Biryani',
    category: 'Family pack Biriyanis',
    price: 599,
    type: 'Non-Veg',
    description:'A delicious blend of tender kalmi and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:135,
    name: 'Tandoori 65 Biryani',
    category: 'Family pack Biriyanis',
    price: 749,
    type: 'Non-Veg',
    description:'A delicious blend of tandoori 65 and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:136 ,
    name: 'Chicken Tikka Biryani',
    category: 'Family pack Biriyanis',
    price: 649,
    type: 'Non-Veg',
    description:'A delicious blend of tender chicken tikka and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:137 ,
    name: 'Lollipop Juicy Biryani',
    category: 'Family pack Biriyanis',
    price: 599,
    type: 'Non-Veg',
    description:'A delicious blend of crispy lollipops and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:138,
    name: 'Kabab Biryani',
    category: 'Family pack Biriyanis',
    price: 549,
    type: 'Non-Veg',
    description:'A delicious blend of tender kababs and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id: 139,
    name: 'Chicken Wings Biryani',
    category: 'Family pack Biriyanis',
    price: 549,
    type: 'Non-Veg',
    description:'A delicious blend of tender chicken wings and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:140,
    name: 'Mr.Special Boneless Biriyani',
    category: 'Family pack Biriyanis',
    price: 689,
    type: 'Non-Veg',
    description:'A special blend of aromatic basmati rice and tender meat, cooked to perfection in a rich, spiced sauce.',
  },
  {
    id: 141,
    name: 'Mutton Fry-Piece Biryani',
    category: 'Family pack Biriyanis',
    price: 749,
    type: 'Non-Veg',
    description:'A delicious blend of tender mutton pieces and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:142,
    name: 'Fish Biryani',
    category: 'Family pack Biriyanis',
    price: 719,
    type: 'Non-Veg',
    description:'A delicious blend of fresh fish and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:143 ,
    name: 'Prawns Biryani',
    category: 'Family pack Biriyanis',
    price: 749,
    type: 'Non-Veg',
    description:'A delicious blend of fresh prawns and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:144,
    name: 'Egg Biryani',
    category: 'Family pack Biriyanis',
    price: 399,
    type: 'Non-Veg',
    description:'A delicious blend of tender eggs and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:145 ,
    name: 'Paneer Biryani',
    category: 'Family pack Biriyanis',
    price: 549,
    type: 'Veg',
    description:'A delicious blend of tender paneer and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:146 ,
    name: 'Mushroom Biryani',
    category: 'Family pack Biriyanis',
    price: 499,
    type: 'Veg',
    description:'A delicious blend of tender mushrooms and aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id:147,
    name: 'Biriyani Rice',
    category: 'Family pack Biriyanis',
    price: 349,
    type: 'Veg',
    description:'A simple and delicious blend of aromatic basmati rice, cooked in a rich, spiced sauce.',
  },
  {
    id: 148,
    name: 'Plain Roti',
    category: 'Indian Breads',
    price: 25,
    type: 'Veg',
    description:'A simple and delicious plain roti, perfect for pairing with any curry or dal.',
  },
  {
    id:149 ,
    name: 'Butter Roti',
    category: 'Indian Breads',
    price: 30,
    type: 'Veg',
    description:'A simple and delicious butter roti, perfect for pairing with any curry or dal.',
  },
  {
    id:150,
    name: 'Plain Naan',
    category: 'Indian Breads',
    price: 35,
    type: 'Veg',
    description:'A simple and delicious plain naan, perfect for pairing with any curry or dal.',
  },
  {
    id:151 ,
    name: 'Butter Naan',
    category: 'Indian Breads',
    price: 40,
    type: 'Veg',
    description:'A simple and delicious butter naan, perfect for pairing with any curry or dal.',
  },
  {
    id:152,
    name: 'Plain Kulcha',
    category: 'Indian Breads',
    price: 35,
    type: 'Veg',
    description:'A simple and delicious plain kulcha, perfect for pairing with any curry or dal.',
  },
  {
    id: 153,
    name: 'Butter Kulcha',
    category: 'Indian Breads',
    price: 40,
    type: 'Veg',
    description:'A simple and delicious butter kulcha, perfect for pairing with any curry or dal.',
  },
  {
    id: 154,
    name: 'Garlic Naan',
    category: 'Indian Breads',
    price: 45,
    type: 'Veg',
    description:'A simple and delicious garlic naan, perfect for pairing with any curry or dal.',
  },
  {
    id:155 ,
    name: 'Aloo Paratha',
    category: 'Indian Breads',
    price: 50,
    type: 'Veg',
    description:'A simple and delicious aloo paratha, perfect for pairing with any curry or dal.',
  },
  {
    id:156 ,
    name: 'Paneer Paratha',
    category: 'Indian Breads',
    price: 60,
    type: 'Veg',
    description:'A simple and delicious paneer paratha, perfect for pairing with any curry or dal.',
  },
  {
    id: 157,
    name: 'Methi Roti',
    category: 'Indian Breads',
    price: 40,
    type: 'Veg',
    description:'A simple and delicious methi roti, perfect for pairing with any curry or dal.',
  },
  {
    id: 158,
    name: 'Stuffed Kulcha',
    category: 'Indian Breads',
    price: 50,
    type: 'Veg',
    description:'A simple and delicious stuffed kulcha, perfect for pairing with any curry or dal.',
  },
  {
    id:159 ,
    name: 'Roti Basket',
    category: 'Indian Breads',
    price: 140,
    type: 'Veg',
    description:'A simple and delicious roti basket, perfect for pairing with any curry or dal.',
  },
  {
    id: 160,
    name: 'Dal Fry',
    category: 'Veg curries',
    price: 110,
    type: 'Veg',
    description:'A simple and delicious dal fry, perfect for pairing with any roti or naan.',
  },
  {
    id: 161,
    name: 'Dal Tadka',
    category: 'Veg curries',
    price: 120,
    type: 'Veg',
    description:'A simple and delicious dal tadka, perfect for pairing with any roti or naan.',
  },
  {
    id:162 ,
    name: 'Kadai Veg',
    category: 'Veg curries',
    price: 139,
    type: 'Veg',
    description:'A simple and delicious kadai veg, perfect for pairing with any roti or naan.',
  },
  {
    id:163 ,
    name: 'Palak Paneer',
    category: 'Veg curries',
    price: 169,
    type: 'Veg',
    description:'A simple and delicious palak paneer, perfect for pairing with any roti or naan.',
  },
  {
    id: 164,
    name: 'Paneer Kolhapuri',
    category: 'Veg curries',
    price: 169,
    type: 'Veg',
    description:'A simple and delicious paneer kolhapuri, perfect for pairing with any roti or naan.',
  },
  {
    id:165 ,
    name: 'Paneer Kadai',
    category: 'Veg curries',
    price: 169,
    type: 'Veg',
    description:'A simple and delicious paneer kadai, perfect for pairing with any roti or naan.',
  },
  {
    id:166 ,
    name: 'Kaju Masala',
    category: 'Veg curries',
    price: 179,
    type: 'Veg',
    description:'A simple and delicious kaju masala, perfect for pairing with any roti or naan.',
  },
  {
    id:167 ,
    name: 'Panner Tikka Masala',
    category: 'Veg curries',
    price: 169,
    type: 'Veg',
    description:'A simple and delicious paneer tikka masala, perfect for pairing with any roti or naan.',
  },
   {
    id:168 ,
    name: 'Panner Butter Masala',
    category: 'Veg curries',
    price: 169,
    type: 'Veg',
    description:'A simple and delicious paneer butter masala, perfect for pairing with any roti or naan.',
  },
  {
    id:169 ,
    name: 'Panner Kheema Masala',
    category: 'Veg curries',
    price: 169,
    type: 'Veg',
    description:'Crumbled paneer cooked in a rich, spiced masala gravy—flavorful, hearty, and satisfying.',
  },
  {
    id:170 ,
    name: 'Mushroom Kadai',
    category: 'Veg curries',
    price: 149,
    type: 'Veg',
    description:'Juicy mushrooms cooked in a rich, spicy kadai masala with bell peppers and aromatic spices.',

  },
  {
    id:171 ,
    name: 'Mushroom Masala',
    category: 'Veg curries',
    price: 149,
    type: 'Veg',
    description:'Tender mushrooms simmered in a rich, flavorful masala gravy—spicy, aromatic, and comforting.',

  },
  {
    id:172 ,
    name: 'Aloo Gobi Masala',
    category: 'Veg curries',
    price: 139,
    type: 'Veg',
    description:'A classic mix of potatoes and cauliflower cooked in a flavorful, spiced masala—simple, hearty, and delicious.',

  },
  {
    id:173,
    name: 'Matar Paneer',
    category: 'Veg curries',
    price: 169,
    type: 'Veg',
    description:'Soft paneer and green peas cooked in a rich, mildly spiced tomato gravy—creamy and comforting.',

  },
  {
    id:174,
    name: 'Veg Malai Kofta',
    category: 'Veg curries',
    price: 169,
    type: 'Veg',
    description:'Soft vegetable koftas in a rich, creamy malai gravy—mildly sweet, smooth, and indulgent.',

  },
  {
    id:175 ,
    name: 'Veg Makhanwala',
    category: 'Veg curries',
    price: 159,
    type: 'Veg',
    description:'Mixed vegetables cooked in a rich, buttery tomato gravy—creamy, mildly spiced, and indulgent.',

  },
  {
    id:176 ,
    name: 'Veg Hyderabadi',
    category: 'Veg curries',
    price: 149,
    type: 'Veg',
    description:'Mixed vegetables cooked in a rich, aromatic Hyderabadi-style gravy—spicy, flavorful, and traditional.',

  },
  {
    id:177 ,
    name: 'Veg Kolhapuri',
    category: 'Veg curries',
    price: 149,
    type: 'Veg',
    description:'Mixed vegetables in a fiery Kolhapuri-style gravy—spicy, bold, and packed with robust flavors.',

  },
  {
    id:178 ,
    name: 'Andhra Fish Curry',
    category: 'Sea food & Egg curries',
    price: 239,
    type: 'Non-Veg',
    description:'Traditional Andhra-style fish curry simmered in a tangy, spicy gravy with bold regional flavors.',

  },
  {
    id:179 ,
    name: 'Andhra Prawns Curry',
    category: 'Sea food & Egg curries',
    price: 239,
    type: 'Non-Veg',
    description:'Traditional Andhra-style prawns curry simmered in a tangy, spicy gravy with bold regional flavors.',

  },
  {
    id:180 ,
    name: 'Fish Masala',
    category: 'Sea food & Egg curries',
    price: 239,
    type: 'Non-Veg',
    description:'Tender fish cooked in a rich, spiced masala gravy—flavorful, aromatic, and satisfying.',

  },
  {
    id:181 ,
    name: 'Panner Masala',
    category: 'Sea food & Egg curries',
    price: 249,
    type: 'Non-Veg',
    description:'Soft paneer cubes cooked in a rich, spiced tomato-onion gravy—creamy, flavorful, and satisfying.',

  },
  {
    id:182 ,
    name: 'Egg Masala',
    category: 'Sea food & Egg curries',
    price: 139,
    type: 'Non-Veg',
    description:'Fried eggs cooked in a rich, spiced masala gravy—flavorful, aromatic, and satisfying.',

  },
  {
    id:183 ,
    name: 'Egg Kolhapuri',
    category: 'Sea food & Egg curries',
    price: 139,
    type: 'Non-Veg',
    description:'Fried eggs cooked in a fiery Kolhapuri-style gravy—spicy, bold, and packed with robust flavors.',

  },
  {
    id:184 ,
    name: 'Mutton Masala',
    category: 'Mutton curries',
    price: 249,
    type: 'Non-Veg',
    description:'Tender mutton pieces cooked in a rich, spiced masala gravy—flavorful, aromatic, and satisfying.',

  },
  {
    id:185,
    name: 'Mutton Guntur Curry',
    category: 'Mutton curries',
    price: 249,
    type: 'Non-Veg',
    description:'Spicy Guntur-style mutton curry cooked with bold red chillies and aromatic spices—rich, fiery, and full of flavor.',

  },
  {
    id:186,
    name: 'Mutton Kolhapuri',
    category: 'Mutton curries',
    price: 249,
    type: 'Non-Veg',
    description:'Tender mutton pieces cooked in a fiery Kolhapuri-style gravy—spicy, bold, and packed with robust flavors.',

  },
  {
    id:187,
    name: 'Mutton Rogan Josh',
    category: 'Mutton curries',
    price: 249,
    type: 'Non-Veg',
    description:'Tender mutton slow-cooked in a rich, aromatic gravy with traditional spices—deep, flavorful, and indulgent.',

  },
  {
    id:188,
    name: 'White Rice',
    category: 'Rice items',
    price: 59,
    type: 'Veg',
    description:'Steamed fluffy white rice—soft, light, and the perfect base for any curry or dal.',

  },
  {
    id:189,
    name: 'Curd Rice',
    category: 'Rice items',
    price: 69,
    type: 'Veg',
    description:'Comforting curd rice made with creamy yogurt and soft rice, lightly seasoned for a soothing, homely taste.',

  },
  {
    id:190,
    name: 'Ghee Rice',
    category: 'Rice items',
    price: 89,
    type: 'Veg',
    description:'Fragrant basmati rice cooked in pure ghee with aromatic spices—rich, flavorful, and comforting.',

  },
  {
    id:191,
    name: 'Jeera Rice',
    category: 'Rice items',
    price: 89,
    type: 'Veg',
    description:'Aromatic jeera rice cooked with cumin seeds and other spices—light, flavorful, and perfect as a side dish.',

  },
  {
    id:192,
    name: 'Veg Fried Rice / Schezwan Rice ',
    category: 'Rice items',
    price: 109,
    type: 'Veg',
    description:'Veg fried rice stir-fried with fresh vegetables or tossed in spicy Schezwan sauce—light, flavorful, and satisfying.',

  },
  {
    id:193,
    name: 'Veg Garlic Fried Rice /Schezwan Rice',
    category: 'Rice items',
    price: 119,
    type: 'Veg',
    description:'Veg fried rice tossed with aromatic garlic or spicy Schezwan sauce—flavorful, bold, and satisfying.',

  },
  {
    id:194,
    name: 'Gobi Fried Rice / Schezwan Rice',
    category: 'Rice items',
    price: 119,
    type: 'Veg',
    description:'Gobi fried rice stir-fried with fresh vegetables or tossed in spicy Schezwan sauce—light, flavorful, and satisfying.',

  },
  {
    id:195,
    name: 'Mushroom Fried Rice / Schezwan Rice',
    category: 'Rice items',
    price: 129,
    type: 'Veg',
    description:'Mushroom fried rice stir-fried with fresh vegetables or tossed in spicy Schezwan sauce—light, flavorful, and satisfying.',

  },
  {
    id:196,
    name: 'Paneer Fried Rice / Schezwan Rice',
    category: 'Rice items',
    price: 159,
    type: 'Veg',
    description:'Paneer fried rice stir-fried with fresh veggies or tossed in spicy Schezwan sauce—rich, flavorful, and satisfying.',

  },
  {
    id:197,
    name: 'Egg Fried Rice / Schezwan Rice ',
    category: 'Rice items',
    price: 129,
    type: 'Non-Veg',
    description:'Egg fried rice stir-fried with veggies or tossed in spicy Schezwan sauce—light, savory, and flavorful.',

  },
  {
    id:198,
    name: 'Chicken Fried Rice / Schezwan Rice',
    category: 'Rice items',
    price: 139,
    type: 'Non-Veg',
    description:'Chicken fried rice stir-fried with fresh veggies or tossed in spicy Schezwan sauce—savory, aromatic, and satisfying.',

  },
  {
    id:199,
    name: 'Chicken Garlic Fried Rice / Schezwan Rice',
    category: 'Rice items',
    price: 149,
    type: 'Veg',
    description:'Chicken fried rice tossed with garlic or spicy Schezwan sauce—aromatic, bold, and full of flavor.',

  },
  {
    id:200 ,
    name: 'Mixed Non Veg Fried Rice / Schezwan Rice',
    category: 'Rice items',
    price: 189,
    type: 'Non-Veg',
    description:'Mixed non-veg fried rice loaded with chicken, egg, and seafood or tossed in spicy Schezwan sauce—bold, smoky, and flavorful.',

  },
  {
    id:201 ,
    name: 'Mr. Biriyani Special Paneer Fried Rice ',
    category: 'Rice items',
    price: 179,
    type: 'Veg',
    description:'Delicious paneer fried rice tossed with fresh veggies and signature house spices—savory, rich, and satisfying.',

  },
  {
    id:202 ,
    name: 'Mr. Biriyani Special Mushroom Fried Rice ',
    category: 'Rice items',
    price: 159,
    type: 'Veg',
    description:'Flavorful mushroom fried rice tossed with fresh veggies and signature house spices—savory, aromatic, and delicious.',

  },
  {
    id:203 ,
    name: 'Mr. Biriyani Special Chicken Fried Rice',
    category: 'Rice items',
    price: 189,
    type: 'Non-Veg',
    description:'Fragrant chicken fried rice tossed with fresh veggies and signature house spices—savory, aromatic, and satisfying.',

  },
  {
    id:204 ,
    name: 'Veg Noodles / Schezwan Noodles',
    category: 'Noodles',
    price: 109,
    type: 'Veg',
    description:'Veg noodles stir-fried with fresh vegetables or tossed in spicy Schezwan sauce—light, flavorful, and satisfying.',

  },
  {
    id:205 ,
    name: 'Paneer Noodles / Schezwan  Noodles',
    category: 'Noodles',
    price: 119,
    type: 'Veg',
    description:'Paneer noodles stir-fried with veggies or tossed in spicy Schezwan sauce—savory, bold, and delicious.',

  },
  {
    id:206 ,
    name: 'Mushroom Noodles / Schezwan Noodles',
    category: 'Noodles',
    price: 129,
    type: 'Veg',
    description:'Mushroom noodles stir-fried with veggies or tossed in spicy Schezwan sauce—savory, bold, and delicious',

  },
  {
    id:207 ,
    name: 'Chicken Noodles / Schezwan  Noodles ',
    category: 'Noodles',
    price: 139,
    type: 'Non-Veg',
    description:'Chicken noodles stir-fried with veggies or tossed in spicy Schezwan sauce—savory, bold, and satisfying.',

  },
  {
    id:208 ,
    name: 'Egg Noodles / Schezwan  Noodles',
    category: 'Noodles',
    price: 129,
    type: 'Non-Veg',
    description:'Egg noodles stir-fried to perfection or tossed in spicy Schezwan sauce—savory, fiery, and satisfying.',

  },
  {
    id:209 ,
    name: 'Chicken Garlic Noodles / Schezwan  Noodles',
    category: 'Noodles',
    price: 149,
    type: 'Non-Veg',
    description:'Chicken noodles tossed with garlic or spicy Schezwan sauce—aromatic, bold, and full of flavor.',

  },
  {
    id:300,
    name: 'Mixed Non Veg Noodles /schezwan  Noodles',
    category: 'Noodles',
    price: 189 ,
    type: 'Non-Veg',
    description:'Mixed non-veg noodles loaded with chicken, egg, and seafood or tossed in spicy Schezwan sauce—bold, fiery, and flavorful.',

  },
  {
    id:301,
    name: 'Mr. Biriyani Special Chicken Noodles',
    category: 'Noodles',
    price: 189,
    type: 'Non-Veg',
    description:'Juicy chicken noodles stir-fried with fresh veggies and signature house spices—savory, aromatic, and satisfying.',

  },
  {
    id:302,
    name: 'Mr.Biriyani Special Paneer Noodles',
    category: 'Noodles',
    price: 179,
    type: 'Veg',
    description:'Delicious paneer noodles tossed with fresh veggies and house special spices—savory, rich, and flavorful.',

  },
  {
    id:303,
    name: 'Mr.Biriyani Special Mushroom Noodles',
    category: 'Noodles',
    price: 169,
    type: 'Veg',
    description:'Flavorful mushroom noodles tossed with veggies and special house spices—savory, aromatic, and delicious.',

  },
  {
    id:304,
    name: 'Mutton Gongura Fry',
    category: 'Andhra Special Non-Veg Starters',
    price: 169,
    type: 'Non-Veg',
    description:'Crispy fried mutton pieces served with a side of your choice—offering a delicious bite that’s perfect as a starter or main course.',
  },
  {
    id:305,
    name: 'Chicken Saagwala',
    category: 'Chicken curries',
    price: 179,
    type: 'Non-Veg',
    description:'Tender chicken cooked in a rich spinach gravy with aromatic spices—nutritious, flavorful, and comforting.',
  },
  {
    id:306,
    name: 'Lasooni Chicken',
    category: 'Chicken curries',
    price: 179,
    type: 'Non-Veg',
    description:'Juicy chicken cooked with rich garlic flavors and aromatic spices—bold, savory, and irresistible.',
  },
  {
    id:307,
    name: 'Methi Chicken',
    category: 'Chicken curries',
    price: 179,
    type: 'Non-Veg',
    description:'Tender chicken cooked with aromatic methi (fenugreek) flavors—unique, savory, and deeply flavorful.',
  },
  {
    id:308,
    name: 'Kalmi Chicken',
    category: 'Chicken curries',
    price: 179,
    type: 'Non-Veg',
    description:'Tender chicken cooked with aromatic kalmi flavors—unique, savory, and deeply flavorful.',
  },
  {
    id:309,
    name: 'Kadai Chicken',
    category: 'Chicken curries',
    price: 179,
    type: 'Non-Veg',
    description:'Tender chicken cooked in a rich, spicy Kadai gravy—flavorful, aromatic, and satisfying.',
  },
  {
    id:310,
    name: 'Butter Chicken',
    category: 'Chicken curries',
    price: 179,
    type: 'Non-Veg',
    description:'Tender chicken cooked in a rich, creamy butter gravy—delicious, aromatic, and satisfying.',
  },
  {
    id:311,
    name: 'Punjabi Chicken',
    category: 'Chicken curries',
    price: 179,
    type: 'Non-Veg',
    description:'Tender chicken cooked in a rich, aromatic Punjabi gravy—flavorful, spicy, and satisfying.',
  },
  {
    id:312,
    name: 'Chicken Kalimirch',
    category: 'Chicken curries',
    price: 179,
    type: 'Non-Veg',
    description:'Tender chicken cooked in a rich, spicy Kalimirch gravy—flavorful, aromatic, and satisfying.',
  },
  {
    id:313,
    name: 'Chicken Hyderabadi',
    category: 'Chicken curries',
    price: 179,
    type: 'Non-Veg',
    description:'Tender chicken cooked in a rich, aromatic Hyderabadi gravy—flavorful, spicy, and satisfying.',
  },
  {
    id:314,
    name: 'Chicken Tikka Masala',
    category: 'Chicken curries',
    price: 189,
    type: 'Non-Veg',
    description:'Tender chicken cooked in a rich, creamy masala gravy—delicious, aromatic, and satisfying.',
  },
  {
    id:315,
    name: 'Guntur Chicken Curry',
    category: 'Chicken curries',
    price: 179,
    type: 'Non-Veg',
    description:'Tender chicken cooked in a rich, aromatic Guntur gravy—flavorful, spicy, and satisfying.',
  },
  {
    id:316,
    name: 'Mughlai Chicken Curry',
    category: 'Chicken curries',
    price: 189,
    type: 'Non-Veg',
    description:'Tender chicken cooked in a rich, aromatic Mughlai gravy—flavorful, spicy, and satisfying.',
  },
  {
    id:317,
    name: 'Chicken Kolhapuri',
    category: 'Chicken curries',
    price: 179,
    type: 'Non-Veg',
    description:'Tender chicken cooked in a rich, aromatic Kolhapuri gravy—flavorful, spicy, and satisfying.',
  },
  {
    id:318,
    name: 'Mr. Biriyani Special Chicken Curry',
    category: 'Chicken curries',
    price: 199,
    type: 'Non-Veg',
    description:'A special blend of aromatic spices and tender chicken—delicious, flavorful, and perfect for a hearty meal.',
  },
   
   
];
